### ISSUE TITLE
error: no field or member function named 'exec' in 'Build'

### ISSUE THREAD

**Issue by tritao** [fubark/zig-v8#10]
I have tested this on Linux and Windows and am seeing the same build error.

This is with https://github.com/fubark/zig-v8/commit/10654d4eed3e6fb4ebc5407577d779cc4235955a, which added support for ` 0.12.0-dev`, I'm a bit of a Zig newbie, so not sure how to fix this yet.
 @almmiko any idea?

**`zig version`** : `0.12.0-dev.1286+cc394431a` 

`zig build get-tools`
```
zig-v8\build.zig:639:23: error: no field or member function named 'exec' in 'Build'
            _ = self.b.exec(&.{ "git", "clone", "--depth=1", "--branch", v8_rev, "https://chromium.googlesource.com/v8/v8.git", "v8" });
                ~~~~~~^~~~~
C:\dev\zig-windows-x86_64-0.12.0-dev.1286+cc394431a\lib\std\Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
referenced by:
    create: C:\dev\zig-v8\build.zig:568:27
    createGetV8: C:\dev\zig-v8\build.zig:355:36
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Comment by almmiko** [comment]
Hey @tritao zig no longer has the `exec` method. It was renamed to `run`. See https://github.com/ziglang/zig/commit/fd2239bde9e2051a32fb25c50c732a40d4afccd0

**Comment by tritao** [comment]
> Hey @tritao zig no longer has the `exec` method. It was renamed to `run`. See [ziglang/zig@fd2239b](https://github.com/ziglang/zig/commit/fd2239bde9e2051a32fb25c50c732a40d4afccd0)

Thanks, yeah I forgot to update this. I found that commit earlier, though there is still another issue after this one is fixed:

```
/home/joao/dev/zig-linux-x86_64-0.12.0-dev.1270+6c9d34bce/lib/std/heap.zig:37:13: error: C allocator is only available when linking against libc
            @compileError("C allocator is only available when linking against libc");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/joao/dev/zig-linux-x86_64-0.12.0-dev.1270+6c9d34bce/lib/std/c/linux.zig:302:12: error: dependency on libc must be explicitly specified in the build command
pub extern "c" fn posix_memalign(memptr: *?*anyopaque, alignment: usize, size: usize) c_int;
           ^~~
/home/joao/dev/zig-linux-x86_64-0.12.0-dev.1270+6c9d34bce/lib/std/c/linux.zig:303:12: error: dependency on libc must be explicitly specified in the build command
pub extern "c" fn malloc_usable_size(?*const anyopaque) usize;
           ^~~
/home/joao/dev/zig-linux-x86_64-0.12.0-dev.1270+6c9d34bce/lib/std/c.zig:246:12: error: dependency on libc must be explicitly specified in the build command
pub extern "c" fn free(?*anyopaque) void;
```

Any idea? I can send a PR to fix this one.

**Comment by theoparis** [comment]
It seems like https://github.com/fubark/zig-v8/blob/master/build.zig#L615 needs to use `self.b.allocator` instead of `c_allocator`.

Edit: after fixing this locally I ran into a python issue:
```
Traceback (most recent call last):
  File "/home/theo/dev/dumbasscomp/zig-v8/parse_deps.py", line 22, in <module>
    main()
  File "/home/theo/dev/dumbasscomp/zig-v8/parse_deps.py", line 18, in main
    exec(deps_str, globals(), out)
  File "<string>", line 64, in <module>
NameError: name 'Str' is not defined. Did you mean: 'str'?
unable to spawn the following command: ExitCodeFailure
python3 parse_deps.py v8/DEPS
error: the following build command failed with exit code 1:
/home/theo/dev/dumbasscomp/zig-v8/zig-cache/o/4cbe2653d3f92c33ab75a848a38af9e3/build /home/theo/zig/zig /home/theo/dev/dumbasscomp/zig-v8 /home/theo/dev/dumbasscomp/zig-v8/zig-cache /home/theo/.cache/zig --seed 0x16bf1401 -Dcpu=baseline -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSmall get-v8

```
Assigning `Str = str` fixes that but then I ran into:
```
thread 111399 panic: attempt to use null value
/home/theo/dev/dumbasscomp/zig-v8/build.zig:592:41: 0x38a830 in parseDep (build)
        const val = deps.object.get(key).?;
                                        ^
/home/theo/dev/dumbasscomp/zig-v8/build.zig:606:38: 0x38b23f in getDep (build)
        const dep = try self.parseDep(deps, key);
                                     ^
/home/theo/dev/dumbasscomp/zig-v8/build.zig:683:24: 0x366708 in make (build)
        try self.getDep(deps, "buildtools/third_party/libc++/trunk", "v8/buildtools/third_party/libc++/trunk");

```

**Comment by almmiko** [comment]
Could you try this PR https://github.com/fubark/zig-v8/pull/11? 
Tested the build on Linux with zig v0.12.0-dev.1327+256ab68a9
